### ISSUE TITLE
Contact forms on contact and job postings pages redirect needs to be fixed

### ISSUE THREAD

**Issue by JohnLZeller** [OSURoboticsClub/Website#32]
Currently, when someone sends a message through the contact form, they get an error page because wordpress puts a / between the url and the # that contact form 7 uses. Like this, http://groups.engr.oregonstate.edu/osurc/jobs/#wpcf7-f189-o1

**Comment by Gzxgzxgzx** [comment]
Outdated issue. Contact forms now functional.
