### ISSUE TITLE
Error uploading new media

### ISSUE THREAD

**Issue by Nrpickle** [OSURoboticsClub/Website#34]
I received the following error when attempting to upload a new file using the media interface:

[Error](https://lh5.googleusercontent.com/fHYLI9KGwCAn3h_jkK3j2ugj0Htn9sdUPpazGwL41Xt-iloEOcxDr0Z25TnU9mJro9FCAtQr_EI=w926-h806).

**Comment by JohnLZeller** [comment]
To keep the site secure, apache needs to be made owner of the uploads directory under wp-content. I do not have permissions to make this happen, so I am contacting web services.

**Comment by JohnLZeller** [comment]
Uploading new media now works!
