### ISSUE TITLE
Embed the club calendar into the website

### ISSUE THREAD

**Issue by JohnLZeller** [OSURoboticsClub/Website#36]
rather than linking away from the site

**Comment by JohnLZeller** [comment]
Here is the embed code:

```html
<iframe src="https://www.google.com/calendar/embed?src=o82vn4hsclbtvmgmde1316j200%40group.calendar.google.com&ctz=America/Los_Angeles" style="border: 0" width="800" height="600" frameborder="0" scrolling="no"></iframe>
```

**Comment by Nrpickle** [comment]
Not sure if this is still the correct embed code.\

**Comment by Nrpickle** [comment]
new source: https://calendar.google.com/calendar/embed?src=b8ths75dtv3jnkjja6ijq28jl8%40group.calendar.google.com&ctz=America/Los_Angeles

**Comment by Gzxgzxgzx** [comment]
Working on this right now.

**Comment by Gzxgzxgzx** [comment]
Fixed: http://osurobotics.club/calendar
