### ISSUE TITLE
Add some basic SEO

### ISSUE THREAD

**Issue by Nrpickle** [OSURoboticsClub/Website#45]
![image](https://cloud.githubusercontent.com/assets/2948829/12618589/620cf544-c4c9-11e5-8135-eba429586f63.png)

**Comment by Gzxgzxgzx** [comment]
Added robots.txt, updated description, added keywords meta tag. Waiting to see that Google can find robots.txt before closing.

**Comment by Gzxgzxgzx** [comment]
Moved robots.txt to the right directory (top-level directory for the WP install)

**Comment by Gzxgzxgzx** [comment]
Google successfully crawled the website this morning.
