### ISSUE TITLE
Update Text Blurbs on Main Site

### ISSUE THREAD

**Issue by Nrpickle** [OSURoboticsClub/Website#50]
![image](https://cloud.githubusercontent.com/assets/2948829/12854038/44c42294-cbec-11e5-96bc-2a05150eee8d.png)

**Comment by Gzxgzxgzx** [comment]
Mars Rover, Underwater updated, still need an updated blurb from Aerial.

**Comment by Gzxgzxgzx** [comment]
Aerial updated.
