### ISSUE TITLE
Constitution link on about page is broken

### ISSUE THREAD

**Issue by Nrpickle** [OSURoboticsClub/Website#54]
[Oregon State Robotics Club Constitution 2015 final.pdf](https://github.com/OSURoboticsClub/Website/files/120033/Oregon.State.Robotics.Club.Constitution.2015.final.pdf)

**Comment by Gzxgzxgzx** [comment]
Hmm. How did this happen.

**Comment by Gzxgzxgzx** [comment]
Fixed. Still unsure how the PDF was deleted.
