### ISSUE TITLE
Image Scaling and Alignment - Clab Display

### ISSUE THREAD

**Issue by caperren** [OSURoboticsClub/Website#57]
We'd like images cycling through the box to automatically scale to height or width, whichever is the larger dimension per image. Then, have that image centered in the display box.

**Comment by Gzxgzxgzx** [comment]
The scaling is set to cover. It should already be doing this. Is it not?

**Comment by Gzxgzxgzx** [comment]
Oh, I see. Alright.

**Comment by Gzxgzxgzx** [comment]
Going to give an ETA on this as ~1 week (since exams this/next week). I will try to complete it earlier if I can.

**Comment by caperren** [comment]
Sounds good. No rush. :)
