### ISSUE TITLE
Clab Display Page Adjustments

### ISSUE THREAD

**Issue by caperren** [OSURoboticsClub/Website#58]
We'd like to add  info to the header bar that will have the OSURC Logo (aligned left), date (aligned center), and time (aligned right). Also, we'd like a small overlay that we can put text into in the bottom right corner of where the cycling images are for putting general clab information, like who to email for access to the clab. Preferably it'd be nice if the text can be edited through wordpress, but not necessary immediately. See below photo for clarification.

![revisions for clab display 2-18-16](https://cloud.githubusercontent.com/assets/4566591/13162161/beafb8e6-d657-11e5-98e6-bcc89ea25383.png)

**Comment by Gzxgzxgzx** [comment]
Working on this today.

**Comment by Gzxgzxgzx** [comment]
Alright. The last set of changes affected this calendar unintentionally. I had checked briefly to make sure this wouldn't happen, but I was wrong. I'm going to work on a fix for this tonight and Wednesday.

**Comment by Gzxgzxgzx** [comment]
![CLAB Calendar](http://i.imgur.com/qV7Dyrlg.png)
